(M) As a visitor on the categories page I want to view tiles of current categories so that I can select what I'm interested in.
bethios/sacredArt pull request #14
Opened 2017-05-29 20:47 UTC by bethios

https://trello.com/c/GMzPLpOD/33-m-as-a-visitor-on-the-categories-page-i-want-to-view-tiles-of-current-categories-so-that-i-can-select-what-i-m-interested-in

https://sacred-art-development.herokuapp.com/categories

![screenshot 2017-05-29 15 44 15](https://cloud.githubusercontent.com/assets/21066579/26561701/06baa504-4486-11e7-872d-25ce4ab47186.png)

2017-05-29 20:47 UTC, bethios commented
![](https://github.trello.services/images/mini-trello-icon.png) [(M) As a visitor on the categories page I want to view tiles of current categories so that I can select what I'm interested in.](https://trello.com/c/GMzPLpOD/33-m-as-a-visitor-on-the-categories-page-i-want-to-view-tiles-of-current-categories-so-that-i-can-select-what-i-m-interested-in)

2017-05-30 21:03 UTC, cblant20 requested changes

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  color: white;
is this the secondary font color? is there somewhere else you can declare it?

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  color: white;
all colors should be in variables

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +  font-size: 2.85em;
variable plz :)

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +  color: $accent
good naming here

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +iframe{
eeek iframes are bad. If you can avoid this, avoid this!!!!!

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +  font-size: 1.25em;
Sass variable plz

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +  font-size: 1.2em;
variable here

2017-05-30 21:03 UTC, cblant20 commented on app/assets/stylesheets/welcome.scss
> +    font-size: 1.75em;
variableeee 🐙

2017-05-30 21:03 UTC, cblant20 commented on app/controllers/welcome_controller.rb
> +    @instagrams = response["data"]
instagrams plural? is that access token something that needs to be private?

2017-05-30 21:03 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +        <%= link_to "ORIGINAL ART" %>
do these exist?

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/_email.html.erb
> +<p><%= mail_to('sacredartstore@gmail.com')%></p>
protect this from spam

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/_email.html.erb
> +<p><%= mail_to('sacredartsubmissions@gmail.com') %></p>
protect this from spam

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/_mailinglist.html.erb
> +      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_dd6462c0ac2ea6e4fcc5f8a07_7573d093b0" tabindex="-1" value=""></div>
what's up with inline styling?

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/categories.html.erb
> +      <%= image_tag('categories/original.jpg', :alt => 'original art category photo', :class => 'categoryImage') %>
for accessibility it's better to describe what the photo is. If this is something that will be changed by your client, make sure to include it in the CMS

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/categories.html.erb
> +      <%= image_tag('categories/jewelry.jpg', :alt => 'jewelry category photo', :class => 'categoryImage') %>
your classes should be named with dashes category-image like standard CSS

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/categories.html.erb
> +      <p class="categoryLabel">WEARABLES</p>
this should be category-label
make sure you are following naming conventions and best practices for the languages

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/contact.html.erb
> +      <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1Mzqwzw1l67n9pskWjsMdyERVkCY"  height="480"></iframe>
is this the map that google maps tells you to embed? You shouldn't be using iframes.

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/submissions.html.erb
> +    <%= image_tag('jewelry.jpg', alt: 'constellation necklaces on cards, clock hand earrings on cards', class: 'content-container side-image')%>
these aren't clickable? why are they here?

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/submissions.html.erb
> +          <li><p>JPGs of your work (at least 3 but as many as 10)</p></li>
3-10 images of your work in JPG format

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/submissions.html.erb
> +          <li><p>Link to your online portfolio, website, or online shop</p></li>
online is repeated

2017-05-30 21:03 UTC, cblant20 commented on app/views/welcome/submissions.html.erb
> +          new design lines. And by all means please do add us to your e-newsletter contact list!</p>
remove the "And" from the final sentence

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +    context "goes to Contact page and shows info" do
remove the shows info from the top.

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +        page.has_css?('row .col-sm-6 iframe', visible: :show)
this is not really checking that the iframe is working, just that you have one on the page

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +        visit '/contact'
this is not checking that the address is there, just VISIT

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +        page.has_css?('row .col-sm-6 div', text: "GENERAL INQUIRIES:")
also not checking the email address

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +      it "shows store hours" do
also not actually showing the store hours

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +        visit '/submissions'
look for the image itself

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +        page.has_css?('.instagram-image')
make sure it's loading more than 1

2017-05-30 21:03 UTC, cblant20 commented on spec/features/welcome_spec.rb
> +      it "shows images" do
make sure the category count is correct and that they aren't all the same

2017-05-31 15:30 UTC, merged