Navbar
bethios/sacredArt pull request #2
Opened 2017-05-24 00:19 UTC by bethios

I'm having problems with heroku set up re: sqlite.  hopefully i can bug you on it.

2017-05-24 23:08 UTC, bethios commented
https://sacred-art-development.herokuapp.com/

2017-05-26 16:57 UTC, bethios commented
![](https://github.trello.services/images/mini-trello-icon.png) [(S) As a visitor on the landing page I want to see a menu so I can know where I want to navigate to.](https://trello.com/c/DnY3LTQD/27-s-as-a-visitor-on-the-landing-page-i-want-to-see-a-menu-so-i-can-know-where-i-want-to-navigate-to)

2017-05-26 22:17 UTC, cblant20 commented
shop does not work from the menu

2017-05-26 22:18 UTC, cblant20 commented
Artists doesn't work from the responsive menu
Responsive menu font is a bit huge

2017-05-26 22:18 UTC, cblant20 commented
this is missing the test passing screenshot

2017-05-26 22:50 UTC, cblant20 requested changes

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  font-family: 'Josefin Sans', sans-serif;
you don't want a secondary and have sans-serif as your tertiary?

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  color: $blackish;
is this your main font? does this need to be here and body?

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  height: 90px;
you sure you want a static height here?

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  margin: 0px;
is this inside content-container?  if not, you don't need to set margin 0 here since body has it

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +  color: $blackish;
if this hasn't been overridden somewhere, you don't need to reset it

2017-05-26 22:50 UTC, cblant20 commented on app/assets/stylesheets/application.scss
> +@media screen and (min-width: 884px) {
desktop standard is 1024px

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +      <li class="nav-li"><%= link_to "ABOUT", about_path %></li>
can't you just use the nav-links class for this style instead of adding a new style to all of them?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +        <%= link_to "BEAUTY" %>
at some point, you will make this dynamic? Is that a card?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +  <%= link_to image_tag("sa_logo_small.png", :alt => "Sacred Art Logo", :class => "logo"), index_path %>
instead of this being built into this page, this should be a partial with a yield.

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +    <p><strong>ADDRESS:</strong><br>
do you want this to be manageable?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +    <p><strong>SPRING HOURS</strong><br>
card to make this dynamic?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +    <p><strong>SPRING HOURS</strong><br>
what does spring hours mean? should this not just be Hours?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +  <div class="col-sm-4 footer-col">
if this information is also used on contact it should be managed in one place?

2017-05-26 22:50 UTC, cblant20 commented on app/views/layouts/application.html.erb
> +    <div id="mc_embed_signup">
same question here

2017-05-27 15:22 UTC, merged